name: ðŸŽ¯ Dart Packages

on:
  push:
    branches: [main]
  pull_request:
    types:
      - closed

jobs:
  geography:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - uses: hrishikesh-kadam/setup-lcov@v1

      - name: ðŸ‘· Build Geography
        working-directory: geography
        run: make all

      - name: ðŸš€ Publish geography
        uses: RatakondalaArun/pub.dev-cd@v1.0.0
        with:
          creditionals: ${{secrets.PUB_DEV_CREDENTIALS}}
          package_path: geography

  cobertura:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - uses: hrishikesh-kadam/setup-lcov@v1

      - name: ðŸ‘· Build Cobertura
        working-directory: cobertura
        run: make all

      - name: ðŸš€ Publish cobertura
        uses: RatakondalaArun/pub.dev-cd@v1.0.0
        with:
          creditionals: ${{secrets.PUB_DEV_CREDENTIALS}}
          package_path: cobertura

